WITH AvailableCars AS (
    SELECT c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR AS c
    WHERE c.CAR_TYPE IN ('세단', 'SUV')
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
        WHERE h.CAR_ID = c.CAR_ID
        AND h.START_DATE <= '2022-11-30'
        AND h.END_DATE >= '2022-11-01'
    )
),
DiscountPlans AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE IN ('세단', 'SUV')
),
CalculatedFees AS (
    SELECT ac.CAR_ID, ac.CAR_TYPE,
    ROUND(ac.DAILY_FEE * 30 * (1 - dp.DISCOUNT_RATE / 100.0)) AS FEE
    FROM AvailableCars AS ac
    JOIN DiscountPlans AS dp ON ac.CAR_TYPE = dp.CAR_TYPE
    WHERE ROUND(ac.DAILY_FEE * 30 * (1 - dp.DISCOUNT_RATE / 100.0)) BETWEEN 500000 AND 1999999
)
SELECT CAR_ID, CAR_TYPE, FEE
FROM CalculatedFees
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
