-- 코드를 입력하세요
SELECT r2.FOOD_TYPE , r2.REST_ID , r2.REST_NAME, r2.FAVORITES
FROM REST_INFO as r2,
(SELECT r1.FOOD_TYPE as r1_Food_Type,MAX(FAVORITES) as r1_Favorites
FROM REST_INFO as r1
GROUP BY r1.FOOD_TYPE) as r1
WHERE r1.r1_Food_Type = r2.FOOD_TYPE and r1.r1_Favorites = r2.FAVORITES
ORDER BY r2.FOOD_TYPE DESC