-- 코드를 입력하세요
WITH TOTAL AS
(
    SELECT count(*) as total_2021_user
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
,
USER_IN_2021 AS
(
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT 
    YEAR(SALES_DATE) as YEAR,
    MONTH(SALES_DATE) as MONTH ,
    COUNT(DISTINCT(USER_ID)) as PURCHASED_USERS ,
    ROUND(COUNT(DISTINCT(USER_ID)) /  total_2021_user,1) as PUCHASED_RATIO

FROM ONLINE_SALE,TOTAL
WHERE USER_ID in (SELECT USER_ID FROM USER_IN_2021)
GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE)