-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR 
FROM FIRST_HALF as FIRST_HALF , (
SELECT FLAVOR,SUM(TOTAL_ORDER) as total_order
FROM JULY
GROUP BY FLAVOR) as JULY_SUM
WHERE FIRST_HALF.FLAVOR = JULY_SUM.FLAVOR
ORDER BY FIRST_HALF.TOTAL_ORDER + JULY_SUM.total_order DESC
LIMIT 3
